//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthTextAnalytics.SampleData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sampledata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sampledata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthTextAnalytics.SampleData.Sampledata", typeof(Sampledata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 12-year old girl with known hyperagglutinability, presented to the emergency department with a 2-week history 
        ///of headeaches and examination right side indicated with conduction facial weakness Neurologic sensorineural hearing loss Weber&apos;s test
        ///demonstrating on the right head revealed temporal bone lateralizing on the , and the Magnetic resonance imaging
        ///severe structural defects indication of of the of the right petrous cerebral infarction.
        /// </summary>
        public static string SamplePatientTextNote1 {
            get {
                return ResourceManager.GetString("SamplePatientTextNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr Tan Ah Kow was accompanied by his son, Mr Tan Ah Beng, for the examination.
        ///Mr Tan is a 55 year old man, who is divorced, and unemployed. Mr Tan is currently
        ///living with his son, Ah Beng, in Ah Beng’s flat. Mr Tan Ah Beng informed me that
        ///Mr Tan Ah Kow used to work as a cleaner.
        ///Mr Tan Ah Kow has a history of medical conditions. He has had hypertension and
        ///hyperlipidemia since 1990 and suffered several strokes in 2005. He subsequently
        ///developed heart problems (cardiomyopathy), cardiac failure and c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SamplePatientTextNote2 {
            get {
                return ResourceManager.GetString("SamplePatientTextNote2", resourceCulture);
            }
        }
    }
}
